// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://haagipczduauluvabymt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhhYWdpcGN6ZHVhdWx1dmFieW10Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ2MzQwNjcsImV4cCI6MjA2MDIxMDA2N30.GODYJ9_mQK5cLbHJG5rquW6djzz55gm_eFIvGe4B1is";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);